<?php

return [
    'matematica' => [
        'ano1' => [
            'titulo' => 'Matemática 1º Ano',
            'faixa' => '6 a 7 anos',
            'introducao' => 'Vamos contar, ver cores, formas e descobrir os números ao nosso redor.',
            'questoes' => [
                ['pergunta' => 'Quantas maçãs estão na árvore?', 'opcoes' => ['2', '4', '3'], 'resposta' => '3', 'explicacao' => 'Contando uma a uma, temos três maçãs.', 'emoji' => '🍎🍎🍎'],
                ['pergunta' => 'Qual é a cor do sol?', 'opcoes' => ['Amarelo', 'Azul', 'Verde'], 'resposta' => 'Amarelo', 'explicacao' => 'O sol é amarelo e brilhante.', 'emoji' => '☀️'],
                ['pergunta' => 'Quantos balões aparecem?', 'opcoes' => ['5', '2', '4'], 'resposta' => '4', 'explicacao' => 'Contamos quatro balões coloridos.', 'emoji' => '🎈🎈🎈🎈'],
                ['pergunta' => 'Qual forma é um quadrado?', 'opcoes' => ['Tem quatro lados iguais', 'Tem três lados', 'Não tem lados retos'], 'resposta' => 'Tem quatro lados iguais', 'explicacao' => 'O quadrado tem todos os quatro lados do mesmo tamanho.', 'emoji' => '⬛'],
                ['pergunta' => 'Quantos patinhos estão na lagoa?', 'opcoes' => ['3', '1', '2'], 'resposta' => '2', 'explicacao' => 'A lagoa tem dois patinhos nadando.', 'emoji' => '🦆🦆'],
                ['pergunta' => 'Qual é o próximo número na sequência: 1, 2, 3, __?', 'opcoes' => ['4', '5', '6'], 'resposta' => '4', 'explicacao' => 'Depois do três, vem o número quatro.', 'emoji' => '🔢'],
                ['pergunta' => 'Quantos peixinhos nadam no aquário?', 'opcoes' => ['3', '4', '5'], 'resposta' => '3', 'explicacao' => 'Contamos três peixinhos felizes.', 'emoji' => '🐟🐟🐟'],
                ['pergunta' => 'Qual forma é redonda como uma bola?', 'opcoes' => ['Círculo', 'Retângulo', 'Triângulo'], 'resposta' => 'Círculo', 'explicacao' => 'O círculo é redondo e não tem cantos.', 'emoji' => '⚪'],
                ['pergunta' => 'Quantas estrelas brilham no céu?', 'opcoes' => ['5', '6', '4'], 'resposta' => '5', 'explicacao' => 'No céu há cinco estrelinhas.', 'emoji' => '⭐⭐⭐⭐⭐'],
                ['pergunta' => 'O que é maior: um elefante ou um cachorro?', 'opcoes' => ['Elefante', 'Cachorro', 'São iguais'], 'resposta' => 'Elefante', 'explicacao' => 'O elefante é um animal muito grande!', 'emoji' => '🐘'],
                ['pergunta' => 'Quantas laranjas estão no cesto?', 'opcoes' => ['2', '3', '1'], 'resposta' => '2', 'explicacao' => 'Há duas laranjas no cesto.', 'emoji' => '🍊🍊'],
                ['pergunta' => 'Qual forma tem três lados?', 'opcoes' => ['Triângulo', 'Quadrado', 'Círculo'], 'resposta' => 'Triângulo', 'explicacao' => 'O triângulo tem três pontas e três lados.', 'emoji' => '🔺'],
                ['pergunta' => 'Quantos lápis estão sobre a mesa?', 'opcoes' => ['4', '3', '2'], 'resposta' => '3', 'explicacao' => 'A mesa tem três lápis.', 'emoji' => '✏️✏️✏️'],
                ['pergunta' => 'Se você tem 2 balas e ganha 1, com quantas fica?', 'opcoes' => ['3', '4', '2'], 'resposta' => '3', 'explicacao' => 'Dois mais um é igual a três.', 'emoji' => '🍬'],
                ['pergunta' => 'Quantos carros estão na rua?', 'opcoes' => ['2', '3', '4'], 'resposta' => '3', 'explicacao' => 'Há três carrinhos na rua.', 'emoji' => '🚗🚗🚗'],
                ['pergunta' => 'O que usamos para ver a hora?', 'opcoes' => ['Relógio', 'Caderno', 'Lápis'], 'resposta' => 'Relógio', 'explicacao' => 'O relógio nos mostra que horas são.', 'emoji' => '⏰'],
                ['pergunta' => 'Quantas frutas estão na cesta?', 'opcoes' => ['4', '5', '6'], 'resposta' => '5', 'explicacao' => 'A cesta tem cinco frutinhas.', 'emoji' => '🍎🍎🍎🍎🍎'],
                ['pergunta' => 'Qual é a forma de uma fatia de pizza?', 'opcoes' => ['Triângulo', 'Círculo', 'Quadrado'], 'resposta' => 'Triângulo', 'explicacao' => 'Uma fatia de pizza parece muito com um triângulo.', 'emoji' => '🍕'],
                ['pergunta' => 'Quantos foguetes estão no espaço?', 'opcoes' => ['2', '1', '3'], 'resposta' => '2', 'explicacao' => 'Temos dois foguetes voando no espaço.', 'emoji' => '🚀🚀'],
                ['pergunta' => 'Qual dia vem depois de segunda-feira?', 'opcoes' => ['Terça-feira', 'Domingo', 'Quinta-feira'], 'resposta' => 'Terça-feira', 'explicacao' => 'Depois da segunda, vem a terça-feira.', 'emoji' => '📅'],
            ],
        ],
        'ano2' => [
            'titulo' => 'Matemática 2º Ano',
            'faixa' => '7 a 8 anos',
            'introducao' => 'Vamos somar, subtrair, ver tabelas e brincar com medidas.',
            'questoes' => [
                ['pergunta' => 'Quanto é 15 + 4?', 'opcoes' => ['19', '18', '20'], 'resposta' => '19', 'explicacao' => 'Quinze mais quatro é dezenove.', 'emoji' => '🔢'],
                ['pergunta' => 'Quanto é 12 - 5?', 'opcoes' => ['7', '6', '8'], 'resposta' => '7', 'explicacao' => 'Doze menos cinco deixa sete.', 'emoji' => '🔢'],
                ['pergunta' => 'Se eu tenho 12 doces e dou 4 para meu irmão, quantos sobram?', 'opcoes' => ['8', '7', '9'], 'resposta' => '8', 'explicacao' => 'Doze menos quatro sobram oito doces.', 'emoji' => '🍬'],
                ['pergunta' => 'Qual número vem antes do 30?', 'opcoes' => ['29', '31', '28'], 'resposta' => '29', 'explicacao' => 'Antes do trinta vem o vinte e nove.', 'emoji' => '🔢'],
                ['pergunta' => 'O que é mais pesado: 1 kg de algodão ou 1 kg de chumbo?', 'opcoes' => ['Pesam o mesmo', 'O chumbo', 'O algodão'], 'resposta' => 'Pesam o mesmo', 'explicacao' => 'Ambos têm 1 kg, então o peso é igual.', 'emoji' => '⚖️'],
                ['pergunta' => 'Se você tem 6 pirulitos e compra mais 6, quantos ficam?', 'opcoes' => ['12', '10', '11'], 'resposta' => '12', 'explicacao' => 'Seis mais seis é doze.', 'emoji' => '🍭'],
                ['pergunta' => 'Quanto é 10 + 20?', 'opcoes' => ['30', '40', '20'], 'resposta' => '30', 'explicacao' => 'Uma dezena mais duas dezenas são três dezenas (30).', 'emoji' => '🔢'],
                ['pergunta' => 'Quanto é 25 - 5?', 'opcoes' => ['20', '15', '30'], 'resposta' => '20', 'explicacao' => 'Vinte e cinco menos cinco é vinte.', 'emoji' => '🔢'],
                ['pergunta' => 'Quantos dias tem uma semana inteira?', 'opcoes' => ['7 dias', '5 dias', '10 dias'], 'resposta' => '7 dias', 'explicacao' => 'Uma semana tem sete dias.', 'emoji' => '📅'],
                ['pergunta' => 'Quanto é 8 + 7?', 'opcoes' => ['15', '16', '14'], 'resposta' => '15', 'explicacao' => 'Oito mais sete é quinze.', 'emoji' => '🔢'],
                ['pergunta' => 'Qual o dobro de 4?', 'opcoes' => ['8', '6', '10'], 'resposta' => '8', 'explicacao' => 'O dobro é fazer 4 + 4, que dá 8.', 'emoji' => '🔢'],
                ['pergunta' => 'Quantos meses tem um ano?', 'opcoes' => ['12 meses', '10 meses', '6 meses'], 'resposta' => '12 meses', 'explicacao' => 'Um ano completo tem doze meses.', 'emoji' => '📆'],
                ['pergunta' => 'Qual soma faz 20?', 'opcoes' => ['10 + 10', '15 + 10', '5 + 10'], 'resposta' => '10 + 10', 'explicacao' => 'Dez mais dez é igual a vinte.', 'emoji' => '🔢'],
                ['pergunta' => 'Na tabela de frutas, há 3 maçãs e 5 bananas. Quantas frutas há no total?', 'opcoes' => ['8 frutas', '7 frutas', '9 frutas'], 'resposta' => '8 frutas', 'explicacao' => 'Três mais cinco dá oito.', 'emoji' => '📊'],
                ['pergunta' => 'Se você tem uma nota de 10 reais e gasta 3, quanto recebe de troco?', 'opcoes' => ['7 reais', '6 reais', '8 reais'], 'resposta' => '7 reais', 'explicacao' => 'Dez menos três é igual a sete reais.', 'emoji' => '💵'],
                ['pergunta' => 'Quanto é 18 - 9?', 'opcoes' => ['9', '8', '10'], 'resposta' => '9', 'explicacao' => 'Dezoito menos nove é nove.', 'emoji' => '🔢'],
                ['pergunta' => 'Uma caixa tem o formato de qual figura?', 'opcoes' => ['Cubo (ou paralelepípedo)', 'Esfera', 'Cilindro'], 'resposta' => 'Cubo (ou paralelepípedo)', 'explicacao' => 'Uma caixa lembra blocos retangulares ou um cubo.', 'emoji' => '📦'],
                ['pergunta' => 'Qual número está entre 49 e 51?', 'opcoes' => ['50', '48', '52'], 'resposta' => '50', 'explicacao' => 'O número cinquenta está no meio.', 'emoji' => '🔢'],
                ['pergunta' => 'Quanto é 22 - 2?', 'opcoes' => ['20', '24', '18'], 'resposta' => '20', 'explicacao' => 'Vinte e dois menos dois é vinte.', 'emoji' => '🔢'],
                ['pergunta' => 'Se a aula começa às 8h e dura 2 horas, a que horas termina?', 'opcoes' => ['10h', '9h', '11h'], 'resposta' => '10h', 'explicacao' => 'Oito mais duas horas dá dez horas.', 'emoji' => '⏰'],
            ],
        ],
        'ano3' => [
            'titulo' => 'Matemática 3º Ano',
            'faixa' => '8 a 9 anos',
            'introducao' => 'Vamos usar a multiplicação, divisão simples e ler o relógio.',
            'questoes' => [
                ['pergunta' => 'Se há 4 sacolas com 3 maçãs em cada, quantas maçãs há no total?', 'opcoes' => ['12', '10', '14'], 'resposta' => '12', 'explicacao' => 'Quatro vezes três é doze.', 'emoji' => '🍎'],
                ['pergunta' => 'Marina tem 15 figurinhas e quer dividir entre 3 amigas. Quantas cada uma ganha?', 'opcoes' => ['5', '4', '6'], 'resposta' => '5', 'explicacao' => 'Quinze dividido por três é igual a cinco.', 'emoji' => '📚'],
                ['pergunta' => 'Se um pacote traz 5 chocolates e você tem 4 pacotes, quantos chocolates são?', 'opcoes' => ['20', '15', '25'], 'resposta' => '20', 'explicacao' => 'Cinco vezes quatro é vinte.', 'emoji' => '🍬'],
                ['pergunta' => 'Um metro tem quantos centímetros?', 'opcoes' => ['100 centímetros', '10 centímetros', '1000 centímetros'], 'resposta' => '100 centímetros', 'explicacao' => 'Em um metro cabem exatamente 100 centímetros.', 'emoji' => '📏'],
                ['pergunta' => 'A amizade de 2 corações traz 8 sorrisos. Quantos sorrisos cada coração dá, se são iguais?', 'opcoes' => ['4', '3', '5'], 'resposta' => '4', 'explicacao' => 'Oito dividido por dois é quatro.', 'emoji' => '😊'],
                ['pergunta' => 'Quantos lados tem um pentágono?', 'opcoes' => ['5 lados', '4 lados', '6 lados'], 'resposta' => '5 lados', 'explicacao' => 'Penta significa cinco.', 'emoji' => '⬟'],
                ['pergunta' => 'Se a turma tem 5 filas com 4 crianças em cada fila, quantas crianças há?', 'opcoes' => ['20', '18', '24'], 'resposta' => '20', 'explicacao' => 'Cinco vezes quatro são vinte crianças.', 'emoji' => '🎒'],
                ['pergunta' => 'Tico tem 12 bolinhas e divide em 2 caixinhas iguais. Quantas bolinhas em cada?', 'opcoes' => ['6', '5', '7'], 'resposta' => '6', 'explicacao' => 'Doze dividido por dois dá seis.', 'emoji' => '📦'],
                ['pergunta' => 'Qual multiplicação dá 18?', 'opcoes' => ['3 × 6', '4 × 4', '2 × 8'], 'resposta' => '3 × 6', 'explicacao' => 'Três vezes seis é dezoito.', 'emoji' => '🔢'],
                ['pergunta' => 'O ponteiro grande do relógio marca os minutos. Se ele está no 6, quantos minutos são?', 'opcoes' => ['30 minutos', '6 minutos', '15 minutos'], 'resposta' => '30 minutos', 'explicacao' => 'O 6 representa a metade da hora, ou seja, 30 minutos.', 'emoji' => '⌚'],
                ['pergunta' => 'Se 10 amigos sentam em 2 mesas iguais, quantos amigos cabem em cada mesa?', 'opcoes' => ['5', '4', '6'], 'resposta' => '5', 'explicacao' => 'Dez dividido por dois é cinco amigos por mesa.', 'emoji' => '🪑'],
                ['pergunta' => 'A vaca dá 5 litros de leite por dia. Quantos litros em 3 dias?', 'opcoes' => ['15', '10', '20'], 'resposta' => '15', 'explicacao' => 'Cinco litros vezes três dias dá quinze.', 'emoji' => '🥛'],
                ['pergunta' => 'Qual é o número que falta em 3 × __ = 21?', 'opcoes' => ['7', '6', '8'], 'resposta' => '7', 'explicacao' => 'Três vezes sete é vinte e um.', 'emoji' => '❓'],
                ['pergunta' => 'Marta comprou 1 quilo de feijão. Quantas gramas há em um quilo?', 'opcoes' => ['1000 gramas', '100 gramas', '500 gramas'], 'resposta' => '1000 gramas', 'explicacao' => 'Um quilograma (kg) é igual a 1000 gramas.', 'emoji' => '⚖️'],
                ['pergunta' => 'Se uma árvore tem 6 galhos e cada galho tem 2 ninhos, quantos ninhos existem?', 'opcoes' => ['12', '10', '14'], 'resposta' => '12', 'explicacao' => 'Seis vezes dois dão doze ninhos.', 'emoji' => '🐦'],
                ['pergunta' => 'O trem tem 4 vagões com 10 cadeiras em cada. Quantas cadeiras há no trem?', 'opcoes' => ['40', '30', '50'], 'resposta' => '40', 'explicacao' => 'Quatro vezes dez são quarenta cadeiras.', 'emoji' => '🚆'],
                ['pergunta' => 'João leu 15 páginas em 5 dias. Quantas páginas leu em cada dia, lendo o mesmo tanto?', 'opcoes' => ['3', '4', '5'], 'resposta' => '3', 'explicacao' => 'Quinze dividido por cinco dá três páginas por dia.', 'emoji' => '📖'],
                ['pergunta' => 'Qual conta é igual a 24?', 'opcoes' => ['4 × 6', '5 × 5', '3 × 7'], 'resposta' => '4 × 6', 'explicacao' => 'Quatro vezes seis dá vinte e quatro.', 'emoji' => '🔢'],
                ['pergunta' => 'Se um pacote de figurinhas custa R$2,00, quanto custam 4 pacotes?', 'opcoes' => ['R$8,00', 'R$6,00', 'R$10,00'], 'resposta' => 'R$8,00', 'explicacao' => 'Quatro vezes dois é oito reais.', 'emoji' => '💵'],
                ['pergunta' => 'Quanto é o triplo de 5?', 'opcoes' => ['15', '10', '20'], 'resposta' => '15', 'explicacao' => 'Triplo significa vezes três. Três vezes cinco é quinze.', 'emoji' => '🔢'],
            ],
        ],
        'ano4' => [
            'titulo' => 'Matemática 4º Ano',
            'faixa' => '9 a 10 anos',
            'introducao' => 'Vamos usar as quatro operações, conhecer frações e resolver desafios lógicos.',
            'questoes' => [
                ['pergunta' => 'Qual é o resultado de 4 × 5 + 10?', 'opcoes' => ['30', '25', '40'], 'resposta' => '30', 'explicacao' => 'Primeiro multiplicamos (4×5=20), depois somamos 10 (20+10=30).', 'emoji' => '🔢'],
                ['pergunta' => 'Como se lê a fração 1/2?', 'opcoes' => ['Um meio (metade)', 'Um dois', 'Duas partes'], 'resposta' => 'Um meio (metade)', 'explicacao' => 'Lemos 1/2 como um meio ou metade de algo.', 'emoji' => '🍰'],
                ['pergunta' => 'Uma viagem dura 120 minutos. Isso equivale a quantas horas?', 'opcoes' => ['2 horas', '1 hora', '3 horas'], 'resposta' => '2 horas', 'explicacao' => 'Como 1 hora tem 60 minutos, 120 minutos são 2 horas.', 'emoji' => '⏰'],
                ['pergunta' => 'Resolva: 15 + (5 × 2).', 'opcoes' => ['25', '40', '20'], 'resposta' => '25', 'explicacao' => 'Multiplica primeiro: 5 × 2 = 10; depois soma 15 + 10 = 25.', 'emoji' => '❓'],
                ['pergunta' => 'Quantos centímetros tem meio metro?', 'opcoes' => ['50 centímetros', '100 centímetros', '25 centímetros'], 'resposta' => '50 centímetros', 'explicacao' => 'Um metro tem 100 cm, a metade é 50 cm.', 'emoji' => '📏'],
                ['pergunta' => 'Qual conta dá 20 se fizermos 8 + 3 × 4?', 'opcoes' => ['20', '44', '32'], 'resposta' => '20', 'explicacao' => 'Multiplique primeiro: 3 × 4 = 12; somando 8 dá 20.', 'emoji' => '❓'],
                ['pergunta' => 'Se um quadrado tem lado de 5 cm, qual é o seu perímetro?', 'opcoes' => ['20 cm', '25 cm', '15 cm'], 'resposta' => '20 cm', 'explicacao' => 'O quadrado tem 4 lados. 4 vezes 5 cm = 20 cm.', 'emoji' => '⬛'],
                ['pergunta' => 'A loja vende 3 pacotes com 12 peças cada. Quantas peças são ao todo?', 'opcoes' => ['36', '24', '48'], 'resposta' => '36', 'explicacao' => 'Três pacotes vezes doze peças dá trinta e seis.', 'emoji' => '📦'],
                ['pergunta' => 'Quanto é 50 dividido por 5?', 'opcoes' => ['10', '5', '15'], 'resposta' => '10', 'explicacao' => 'Cinquenta dividido por cinco é igual a dez.', 'emoji' => '🔢'],
                ['pergunta' => 'Qual número falta: 10 + __ × 3 = 19?', 'opcoes' => ['3', '4', '2'], 'resposta' => '3', 'explicacao' => 'Três vezes três é nove; dez mais nove dá dezenove.', 'emoji' => '❓'],
                ['pergunta' => 'Se João tem R$50,00 e compra um brinquedo por R$35,00, qual o troco?', 'opcoes' => ['R$15,00', 'R$25,00', 'R$10,00'], 'resposta' => 'R$15,00', 'explicacao' => 'Cinquenta menos trinta e cinco sobra quinze reais.', 'emoji' => '💵'],
                ['pergunta' => 'Como chamamos um ângulo que parece a quina perfeita de um quadrado?', 'opcoes' => ['Ângulo reto', 'Ângulo agudo', 'Ângulo obtuso'], 'resposta' => 'Ângulo reto', 'explicacao' => 'A quina de um quadrado forma um ângulo reto de 90 graus.', 'emoji' => '📐'],
                ['pergunta' => 'Temos 4 carros com 4 rodas cada, e mais um estepe no porta-malas de cada um. Quantos pneus ao todo?', 'opcoes' => ['20', '16', '24'], 'resposta' => '20', 'explicacao' => 'Cada carro tem 5 pneus (4+1). Quatro vezes cinco é 20.', 'emoji' => '🚗'],
                ['pergunta' => 'Qual é o dobro de 45?', 'opcoes' => ['90', '80', '100'], 'resposta' => '90', 'explicacao' => '45 mais 45 (ou 45x2) dá 90.', 'emoji' => '🔢'],
                ['pergunta' => 'Qual destas frações é maior: 1/2 ou 1/4?', 'opcoes' => ['1/2', '1/4', 'São iguais'], 'resposta' => '1/2', 'explicacao' => '1/2 (metade) é maior que 1/4 (um quarto).', 'emoji' => '🍕'],
                ['pergunta' => 'Qual é o resultado de 100 - (30 + 20)?', 'opcoes' => ['50', '90', '40'], 'resposta' => '50', 'explicacao' => 'Primeiro resolve os parênteses: 30+20=50. Depois, 100-50=50.', 'emoji' => '❓'],
                ['pergunta' => 'Se um caderno tem 100 folhas, quantas folhas têm 8 cadernos iguais?', 'opcoes' => ['800', '80', '180'], 'resposta' => '800', 'explicacao' => 'Cem folhas vezes oito cadernos dão oitocentas folhas.', 'emoji' => '📖'],
                ['pergunta' => 'O carro faz 4 voltas de 5 minutos cada. Quanto tempo ele demora?', 'opcoes' => ['20 minutos', '15 minutos', '25 minutos'], 'resposta' => '20 minutos', 'explicacao' => 'Quatro vezes cinco minutos são vinte minutos.', 'emoji' => '🏎️'],
                ['pergunta' => 'Se dividirmos uma pizza em 8 pedaços e comermos 3, qual a fração que sobrou?', 'opcoes' => ['5/8', '3/8', '8/5'], 'resposta' => '5/8', 'explicacao' => 'Oito pedaços menos três sobram cinco. Logo, 5/8.', 'emoji' => '🍕'],
                ['pergunta' => 'Mil metros equivalem a:', 'opcoes' => ['1 Quilômetro (km)', '10 Centímetros', '1 Milímetro'], 'resposta' => '1 Quilômetro (km)', 'explicacao' => 'A sigla "kilo" significa mil, portanto 1 km = 1000 metros.', 'emoji' => '🛣️'],
            ],
        ],
        'ano5' => [
            'titulo' => 'Matemática 5º Ano',
            'faixa' => '10 a 11 anos',
            'introducao' => 'Vamos pensar em problemas compostos, decimais, frações e leitura de dados.',
            'questoes' => [
                ['pergunta' => 'Qual é a forma decimal da fração 1/2?', 'opcoes' => ['0,5', '1,2', '0,2'], 'resposta' => '0,5', 'explicacao' => 'Dividindo 1 por 2 obtemos 0,5 (cinco décimos).', 'emoji' => '🔢'],
                ['pergunta' => 'Se 25% de uma turma de 40 alunos usa óculos, quantos alunos usam óculos?', 'opcoes' => ['10 alunos', '25 alunos', '15 alunos'], 'resposta' => '10 alunos', 'explicacao' => '25% é o mesmo que dividir por 4. 40 dividido por 4 é 10.', 'emoji' => '👓'],
                ['pergunta' => 'Lucas tem 12 balas e divide com 3 amigos. Porém ele guardou 3 para si. Quantas ele dividiu?', 'opcoes' => ['9', '12', '3'], 'resposta' => '9', 'explicacao' => 'Ele tinha 12 e tirou 3 para ele, sobrando 9 balas para dividir.', 'emoji' => '🍬'],
                ['pergunta' => 'Um gráfico de colunas mostra vendas: Jan (20), Fev (30), Mar (50). Qual foi a média mensal?', 'opcoes' => ['Aproximadamente 33', '20', '50'], 'resposta' => 'Aproximadamente 33', 'explicacao' => '20+30+50 = 100. 100 dividido por 3 meses é igual a 33,33.', 'emoji' => '📊'],
                ['pergunta' => 'Uma caixa tem o volume de 2m x 3m x 1m. Qual é o volume total em m³?', 'opcoes' => ['6 m³', '5 m³', '10 m³'], 'resposta' => '6 m³', 'explicacao' => 'O volume é a multiplicação das três medidas: 2 x 3 x 1 = 6.', 'emoji' => '📦'],
                ['pergunta' => 'Se sobra 1/4 da maçã e ela tinha 8 pedaços no total, quantos pedaços sobraram?', 'opcoes' => ['2 pedaços', '4 pedaços', '1 pedaço'], 'resposta' => '2 pedaços', 'explicacao' => 'Um quarto (1/4) de oito é oito dividido por quatro, que dá 2.', 'emoji' => '🍎'],
                ['pergunta' => 'Quanto é R$1,50 + R$2,25?', 'opcoes' => ['R$3,75', 'R$4,00', 'R$3,50'], 'resposta' => 'R$3,75', 'explicacao' => 'Somando reais e centavos: 1+2=3 reais e 50+25=75 centavos.', 'emoji' => '💵'],
                ['pergunta' => 'Se você comprar 3 cadernos por R$15,00 cada, quanto gastará?', 'opcoes' => ['R$45,00', 'R$30,00', 'R$50,00'], 'resposta' => 'R$45,00', 'explicacao' => 'Três vezes quinze dá quarenta e cinco.', 'emoji' => '📓'],
                ['pergunta' => 'Qual fração é equivalente a 2/4?', 'opcoes' => ['1/2', '3/4', '1/3'], 'resposta' => '1/2', 'explicacao' => 'Simplificando 2/4, dividimos ambos por 2 e obtemos 1/2.', 'emoji' => '🍕'],
                ['pergunta' => 'Se um trem viaja a 80 km/h, quantos quilômetros percorre em 2 horas?', 'opcoes' => ['160 km', '100 km', '80 km'], 'resposta' => '160 km', 'explicacao' => 'Oitenta quilômetros por hora vezes duas horas dão 160 km.', 'emoji' => '🚆'],
                ['pergunta' => 'Se você come 2/3 de um bolo dividido em 9 pedaços, quantos pedaços comeu?', 'opcoes' => ['6', '3', '4'], 'resposta' => '6', 'explicacao' => 'Divida 9 por 3 (=3) e multiplique por 2 (=6).', 'emoji' => '🍰'],
                ['pergunta' => 'Qual conta é verdadeira: 5 × 4 + 10 = ?', 'opcoes' => ['30', '40', '50'], 'resposta' => '30', 'explicacao' => 'Cinco vezes quatro é vinte; mais dez dá trinta.', 'emoji' => '❓'],
                ['pergunta' => 'Se 1 kg de carne custa R$40,00, quanto custam 500 gramas?', 'opcoes' => ['R$20,00', 'R$30,00', 'R$15,00'], 'resposta' => 'R$20,00', 'explicacao' => '500g é meio quilo, então custa a metade de R$40,00.', 'emoji' => '🥩'],
                ['pergunta' => 'Tia Ana tinha uma fita de 2 metros. Ela cortou 50 centímetros. Quanto sobrou?', 'opcoes' => ['1,5 metros (150 cm)', '1 metro', '50 centímetros'], 'resposta' => '1,5 metros (150 cm)', 'explicacao' => '2 metros (200 cm) menos 50 cm é igual a 150 cm (ou 1,5m).', 'emoji' => '🎀'],
                ['pergunta' => 'Em um jogo, as moedas caem em Cara ou Coroa. Qual a chance de cair Cara?', 'opcoes' => ['50%', '100%', '25%'], 'resposta' => '50%', 'explicacao' => 'Como só há duas opções, a chance é de metade (50%).', 'emoji' => '🪙'],
                ['pergunta' => 'Uma viagem de avião sai às 14h30 e dura 2h15. Que horas o avião chega?', 'opcoes' => ['16h45', '16h30', '17h00'], 'resposta' => '16h45', 'explicacao' => '14h + 2h = 16h; 30min + 15min = 45min.', 'emoji' => '✈️'],
                ['pergunta' => 'Qual é o resultado de 0,5 + 0,5?', 'opcoes' => ['1,0', '0,10', '0,25'], 'resposta' => '1,0', 'explicacao' => 'Meio mais meio forma um inteiro (1,0).', 'emoji' => '🔢'],
                ['pergunta' => 'Se 1/4 da turma de 32 alunos faltou, quantos alunos faltaram?', 'opcoes' => ['8 alunos', '10 alunos', '6 alunos'], 'resposta' => '8 alunos', 'explicacao' => 'Dividindo trinta e dois por quatro, encontramos oito.', 'emoji' => '🏫'],
                ['pergunta' => 'Como escrevemos "três décimos" em número decimal?', 'opcoes' => ['0,3', '3,0', '0,03'], 'resposta' => '0,3', 'explicacao' => 'O 3 logo após a vírgula indica a casa dos décimos.', 'emoji' => '🔢'],
                ['pergunta' => 'Qual polígono tem 6 lados e 6 vértices?', 'opcoes' => ['Hexágono', 'Pentágono', 'Octógono'], 'resposta' => 'Hexágono', 'explicacao' => 'O prefixo "hexa" indica o número seis.', 'emoji' => '⬡'],
            ],
        ],
    ],
    'portugues' => [
        'ano1' => [
            'titulo' => 'Português 1º Ano',
            'faixa' => '6 a 7 anos',
            'introducao' => 'Aqui a gente brinca com letras, sílabas e as primeiras palavras.',
            'questoes' => [
                ['pergunta' => 'Qual letra começa a palavra "sol"?', 'opcoes' => ['S', 'L', 'T'], 'resposta' => 'S', 'explicacao' => 'A palavra sol começa com a letra S.', 'emoji' => '☀️'],
                ['pergunta' => 'Qual letra começa a palavra "bola"?', 'opcoes' => ['B', 'P', 'D'], 'resposta' => 'B', 'explicacao' => 'A palavra bola começa com B.', 'emoji' => '⚽'],
                ['pergunta' => 'Qual dessas palavras termina com a vogal O?', 'opcoes' => ['Gato', 'Mesa', 'Uva'], 'resposta' => 'Gato', 'explicacao' => 'A palavra G-A-T-O termina com a letra O.', 'emoji' => '🐈'],
                ['pergunta' => 'Qual palavra é um animal?', 'opcoes' => ['Pato', 'Casa', 'Mesa'], 'resposta' => 'Pato', 'explicacao' => 'Pato é um animal que nada no lago.', 'emoji' => '🦆'],
                ['pergunta' => 'A palavra "MACACO" começa com qual sílaba?', 'opcoes' => ['MA', 'CA', 'CO'], 'resposta' => 'MA', 'explicacao' => 'A primeira sílaba de MA-CA-CO é MA.', 'emoji' => '🐒'],
                ['pergunta' => 'Qual palavra rima com "PÃO"?', 'opcoes' => ['Mão', 'Pé', 'Cama'], 'resposta' => 'Mão', 'explicacao' => 'Mão e Pão terminam com o mesmo som ão.', 'emoji' => '🍞'],
                ['pergunta' => 'Qual cor está escondida na palavra "Amarelo"?', 'opcoes' => ['Azul', 'Não tem cor escondida, a palavra É a cor!', 'Roxo'], 'resposta' => 'Não tem cor escondida, a palavra É a cor!', 'explicacao' => 'Amarelo é o nome próprio da cor.', 'emoji' => '💛'],
                ['pergunta' => 'Qual palavra começa com C?', 'opcoes' => ['Cachorro', 'Gato', 'Peixe'], 'resposta' => 'Cachorro', 'explicacao' => 'Cachorro começa com a letra C.', 'emoji' => '🐾'],
                ['pergunta' => 'Qual vogal está no meio da palavra "SOL"?', 'opcoes' => ['O', 'A', 'U'], 'resposta' => 'O', 'explicacao' => 'A letra O fica entre o S e o L.', 'emoji' => '☀️'],
                ['pergunta' => 'Qual palavra é uma fruta?', 'opcoes' => ['Banana', 'Livro', 'Copo'], 'resposta' => 'Banana', 'explicacao' => 'Banana é uma fruta gostosa.', 'emoji' => '🍌'],
                ['pergunta' => 'Qual palavra rima com "COLA"?', 'opcoes' => ['Bola', 'Dado', 'Mesa'], 'resposta' => 'Bola', 'explicacao' => 'Co-la e Bo-la têm sons finais iguais.', 'emoji' => '🧴'],
                ['pergunta' => 'Qual é a primeira letra da palavra "LUA"?', 'opcoes' => ['L', 'M', 'N'], 'resposta' => 'L', 'explicacao' => 'A palavra lua começa com L.', 'emoji' => '🌙'],
                ['pergunta' => 'Quantas sílabas (pedacinhos) tem a palavra "CA-SA"?', 'opcoes' => ['2', '3', '1'], 'resposta' => '2', 'explicacao' => 'Quando falamos, abrimos a boca duas vezes: CA - SA.', 'emoji' => '🏠'],
                ['pergunta' => 'Qual palavra indica comida?', 'opcoes' => ['Maçã', 'Janela', 'Chapéu'], 'resposta' => 'Maçã', 'explicacao' => 'A maçã é uma fruta que comemos.', 'emoji' => '🍎'],
                ['pergunta' => 'Se juntarmos B com A, fazemos o som de:', 'opcoes' => ['BA', 'BO', 'BE'], 'resposta' => 'BA', 'explicacao' => 'B mais A forma a sílaba BA.', 'emoji' => '🔤'],
                ['pergunta' => 'Qual palavra tem um som nasal (feito pelo nariz)?', 'opcoes' => ['Maçã', 'Livro', 'Pato'], 'resposta' => 'Maçã', 'explicacao' => 'O til (~) em maçã faz o som nasal.', 'emoji' => '👃'],
                ['pergunta' => 'Qual palavra começa com F?', 'opcoes' => ['Foca', 'Pato', 'Cama'], 'resposta' => 'Foca', 'explicacao' => 'Foca começa com a letra F.', 'emoji' => '🦭'],
                ['pergunta' => 'Na cantiga "Sapo cururu", qual animal é citado?', 'opcoes' => ['Sapo', 'Cachorro', 'Gato'], 'resposta' => 'Sapo', 'explicacao' => 'A cantiga fala sobre o sapo cururu.', 'emoji' => '🐸'],
                ['pergunta' => 'Qual letra começa a palavra "PIPA"?', 'opcoes' => ['P', 'T', 'S'], 'resposta' => 'P', 'explicacao' => 'A palavra pipa começa com a letra P.', 'emoji' => '🪁'],
                ['pergunta' => 'Qual grupo de letras tem APENAS VOGAIS?', 'opcoes' => ['A, E, I, O, U', 'A, B, C, D', 'Z, X, Y, W'], 'resposta' => 'A, E, I, O, U', 'explicacao' => 'As cinco vogais do nosso alfabeto.', 'emoji' => '🅰️'],
            ],
        ],
        'ano2' => [
            'titulo' => 'Português 2º Ano',
            'faixa' => '7 a 8 anos',
            'introducao' => 'Vamos formar palavras, descobrir ortografia e ler pequenas frases.',
            'questoes' => [
                ['pergunta' => 'Que palavra formamos com sí + la + ba?', 'opcoes' => ['Sílaba', 'Sala', 'Sábia'], 'resposta' => 'Sílaba', 'explicacao' => 'Si + la + ba juntas formam a palavra sílaba.', 'emoji' => '📖'],
                ['pergunta' => 'A palavra "CASA" se escreve com S, mas tem som de:', 'opcoes' => ['Z', 'C', 'X'], 'resposta' => 'Z', 'explicacao' => 'O S no meio de duas vogais ganha som de Z.', 'emoji' => '🏠'],
                ['pergunta' => 'Complete corretamente: A __enina brinca.', 'opcoes' => ['M', 'P', 'T'], 'resposta' => 'M', 'explicacao' => 'A letra M forma a palavra Menina.', 'emoji' => '👧'],
                ['pergunta' => 'Qual palavra é escrita com Ç?', 'opcoes' => ['Palhaço', 'Passaro', 'Vaso'], 'resposta' => 'Palhaço', 'explicacao' => 'Palhaço usa C-cedilha para fazer o som de SS.', 'emoji' => '🤡'],
                ['pergunta' => 'Na frase "O cachorro morde", quem é que morde?', 'opcoes' => ['O cachorro', 'O menino', 'O gato'], 'resposta' => 'O cachorro', 'explicacao' => 'O texto indica claramente que o cachorro realiza a ação.', 'emoji' => '🐾'],
                ['pergunta' => 'Complete a palavra: B__LÃO.', 'opcoes' => ['A', 'E', 'O'], 'resposta' => 'A', 'explicacao' => 'A vogal A forma a palavra BALÃO.', 'emoji' => '🎈'],
                ['pergunta' => 'Qual palavra está escrita de forma errada?', 'opcoes' => ['Caxo', 'Cachorro', 'Chuva'], 'resposta' => 'Caxo', 'explicacao' => 'O correto é cacho, com CH.', 'emoji' => '❌'],
                ['pergunta' => 'A sílaba final de "GIRASSOL" é:', 'opcoes' => ['SOL', 'RAS', 'GI'], 'resposta' => 'SOL', 'explicacao' => 'A palavra se divide em GI-RAS-SOL.', 'emoji' => '🌻'],
                ['pergunta' => 'Qual palavra indica o nome de uma pessoa (Substantivo Próprio)?', 'opcoes' => ['João', 'Menino', 'Cachorro'], 'resposta' => 'João', 'explicacao' => 'João é nome próprio e por isso começa com letra maiúscula.', 'emoji' => '👦'],
                ['pergunta' => 'Qual palavra descreve um animal com casca dura que anda devagar?', 'opcoes' => ['Tartaruga', 'Coelho', 'Passarinho'], 'resposta' => 'Tartaruga', 'explicacao' => 'A tartaruga tem carapaça e anda lentamente.', 'emoji' => '🐢'],
                ['pergunta' => 'Na frase "A flor é cheirosa", a palavra cheirosa nos conta como a flor é. Isso é um:', 'opcoes' => ['Adjetivo (qualidade)', 'Substantivo (nome)', 'Verbo (ação)'], 'resposta' => 'Adjetivo (qualidade)', 'explicacao' => 'Cheirosa descreve uma qualidade da flor.', 'emoji' => '🌸'],
                ['pergunta' => 'O antônimo (oposto) de GRANDE é:', 'opcoes' => ['Pequeno', 'Maior', 'Grosso'], 'resposta' => 'Pequeno', 'explicacao' => 'O contrário de ser grande é ser pequeno.', 'emoji' => '📏'],
                ['pergunta' => 'A palavra "BANANA" tem quantas sílabas?', 'opcoes' => ['3', '2', '4'], 'resposta' => '3', 'explicacao' => 'BA - NA - NA (três pedacinhos).', 'emoji' => '🍌'],
                ['pergunta' => 'Qual palavra tem o encontro de duas consoantes (BR)?', 'opcoes' => ['Braço', 'Bala', 'Boca'], 'resposta' => 'Braço', 'explicacao' => 'O B e o R estão juntos na mesma sílaba.', 'emoji' => '💪'],
                ['pergunta' => 'Qual a pontuação para fazer uma pergunta?', 'opcoes' => ['Ponto de interrogação (?)', 'Ponto final (.)', 'Vírgula (,)'], 'resposta' => 'Ponto de interrogação (?)', 'explicacao' => 'O ponto de interrogação indica que é uma pergunta.', 'emoji' => '❓'],
                ['pergunta' => 'No diminutivo, a palavra "LIVRO" vira:', 'opcoes' => ['Livrinho', 'Livrão', 'Livreiro'], 'resposta' => 'Livrinho', 'explicacao' => 'O sufixo "inho" indica algo menor.', 'emoji' => '📚'],
                ['pergunta' => 'Que palavra usamos para indicar algo que está perto?', 'opcoes' => ['Este / Esta', 'Aquele', 'Longe'], 'resposta' => 'Este / Esta', 'explicacao' => 'Usamos este ou esta para objetos próximos.', 'emoji' => '👇'],
                ['pergunta' => 'Qual dessas palavras está no plural (mais de um)?', 'opcoes' => ['Carros', 'Bola', 'Sol'], 'resposta' => 'Carros', 'explicacao' => 'O "S" no final de "carros" indica que há mais de um.', 'emoji' => '🚗'],
                ['pergunta' => 'Qual letra colocamos antes de P e B nas palavras?', 'opcoes' => ['M', 'N', 'L'], 'resposta' => 'M', 'explicacao' => 'A regra diz que antes de P e B sempre usamos M.', 'emoji' => '🔤'],
                ['pergunta' => 'Qual é a ordem alfabética correta?', 'opcoes' => ['Abelha, Bola, Casa', 'Bola, Abelha, Casa', 'Casa, Bola, Abelha'], 'resposta' => 'Abelha, Bola, Casa', 'explicacao' => 'Segue a ordem do A, B e depois C.', 'emoji' => '📚'],
            ],
        ],
        'ano3' => [
            'titulo' => 'Português 3º Ano',
            'faixa' => '8 a 9 anos',
            'introducao' => 'Vamos interpretar textos, descobrir os verbos e brincar com pontuação.',
            'questoes' => [
                ['pergunta' => 'Leia: "O passarinho cantou no galho da goiabeira". Qual é o verbo da frase?', 'opcoes' => ['Cantou', 'Passarinho', 'Goiabeira'], 'resposta' => 'Cantou', 'explicacao' => 'Cantou é a ação (o que ele fez).', 'emoji' => '🐦'],
                ['pergunta' => 'No texto: "O sol brilhava e a família foi ao parque", onde a família foi?', 'opcoes' => ['Ao parque', 'Ficou em casa', 'À praia'], 'resposta' => 'Ao parque', 'explicacao' => 'O texto afirma explicitamente que foram ao parque.', 'emoji' => '🌳'],
                ['pergunta' => 'Uma história que ensina uma lição de moral no final, geralmente com animais, chama-se:', 'opcoes' => ['Fábula', 'Receita', 'Poesia'], 'resposta' => 'Fábula', 'explicacao' => 'Fábulas são narrativas curtas com lição de moral.', 'emoji' => '🦊'],
                ['pergunta' => 'O plural de "PÃO" é:', 'opcoes' => ['Pães', 'Pãos', 'Pões'], 'resposta' => 'Pães', 'explicacao' => 'A palavra pão faz plural com terminação "ães".', 'emoji' => '🍞'],
                ['pergunta' => 'Qual a separação silábica correta da palavra "CARRO"?', 'opcoes' => ['CAR-RO', 'CA-RRO', 'CARR-O'], 'resposta' => 'CAR-RO', 'explicacao' => 'Os dois "R" devem ficar em sílabas diferentes.', 'emoji' => '🚗'],
                ['pergunta' => 'No trecho: "Ana fez um desenho colorido". "Colorido" é um:', 'opcoes' => ['Adjetivo', 'Substantivo', 'Verbo'], 'resposta' => 'Adjetivo', 'explicacao' => 'Colorido dá uma característica (qualidade) ao desenho.', 'emoji' => '🎨'],
                ['pergunta' => 'Leia: "Eu gosto de maçã, mas prefiro banana." A palavra "mas" indica:', 'opcoes' => ['Oposição/Ideia contrária', 'Soma', 'Tempo'], 'resposta' => 'Oposição/Ideia contrária', 'explicacao' => 'A palavra MAS traz uma ideia contrária ao que foi dito antes.', 'emoji' => '🤔'],
                ['pergunta' => 'O que é um substantivo comum?', 'opcoes' => ['Nomeia coisas, objetos, animais (ex: livro)', 'Nomeia cidades e pessoas (ex: Brasil)', 'Indica ação (ex: correr)'], 'resposta' => 'Nomeia coisas, objetos, animais (ex: livro)', 'explicacao' => 'Nomes genéricos que damos aos seres e objetos da mesma espécie.', 'emoji' => '📦'],
                ['pergunta' => 'Qual acento usamos na palavra "ÁRVORE"?', 'opcoes' => ['Acento Agudo (´)', 'Acento Circunflexo (^)', 'Til (~)'], 'resposta' => 'Acento Agudo (´)', 'explicacao' => 'O acento agudo marca o som aberto na sílaba tônica ÁR.', 'emoji' => '🌳'],
                ['pergunta' => 'Qual palavra é o aumentativo de BOCA?', 'opcoes' => ['Bocarra', 'Bocona', 'Boquinha'], 'resposta' => 'Bocarra', 'explicacao' => 'A forma culta do aumentativo de boca é bocarra.', 'emoji' => '👄'],
                ['pergunta' => 'A frase "Que susto!" deve terminar com qual ponto?', 'opcoes' => ['Ponto de Exclamação (!)', 'Ponto de Interrogação (?)', 'Ponto Final (.)'], 'resposta' => 'Ponto de Exclamação (!)', 'explicacao' => 'A exclamação indica espanto, admiração ou susto.', 'emoji' => '❗'],
                ['pergunta' => 'O coletivo (grupo) de peixes se chama:', 'opcoes' => ['Cardume', 'Bando', 'Matilha'], 'resposta' => 'Cardume', 'explicacao' => 'Cardume é o nome dado a um conjunto de peixes.', 'emoji' => '🐟'],
                ['pergunta' => 'No texto "Ontem nós brincamos muito", a palavra ONTEM indica:', 'opcoes' => ['Tempo passado', 'Tempo futuro', 'Lugar'], 'resposta' => 'Tempo passado', 'explicacao' => 'Ontem marca algo que já aconteceu (passado).', 'emoji' => '🕰️'],
                ['pergunta' => 'A história diz que a menina correu muito. A palavra "muito" é:', 'opcoes' => ['Advérbio de intensidade', 'Verbo', 'Nome'], 'resposta' => 'Advérbio de intensidade', 'explicacao' => 'Indica a quantidade/intensidade com que a ação ocorreu.', 'emoji' => '🏃‍♀️'],
                ['pergunta' => 'Qual dessas palavras está no feminino?', 'opcoes' => ['A rainha', 'O rei', 'O príncipe'], 'resposta' => 'A rainha', 'explicacao' => 'Rainha é o feminino de rei.', 'emoji' => '👑'],
                ['pergunta' => 'Se o céu estava "estrelado", significa que:', 'opcoes' => ['Tinha muitas estrelas', 'Estava chovendo', 'Era dia'], 'resposta' => 'Tinha muitas estrelas', 'explicacao' => 'A palavra estrelado deriva de estrela, indicando muitas no céu.', 'emoji' => '🌌'],
                ['pergunta' => 'Qual é o sujeito (de quem se fala) na frase: "O cão latiu alto"?', 'opcoes' => ['O cão', 'Latiu', 'Alto'], 'resposta' => 'O cão', 'explicacao' => 'O sujeito é quem pratica a ação do verbo (latir).', 'emoji' => '🐕'],
                ['pergunta' => 'Complete com G ou J: __enipapo.', 'opcoes' => ['J', 'G', 'X'], 'resposta' => 'J', 'explicacao' => 'As frutas de origem tupi geralmente são escritas com J.', 'emoji' => '🌳'],
                ['pergunta' => 'Um texto com instruções de como preparar uma comida é uma:', 'opcoes' => ['Receita', 'Poesia', 'Notícia'], 'resposta' => 'Receita', 'explicacao' => 'Receitas culinárias ensinam a preparar alimentos.', 'emoji' => '🍳'],
                ['pergunta' => 'A palavra "CAFÉ" é paroxítona ou oxítona?', 'opcoes' => ['Oxítona (sílaba forte no final)', 'Paroxítona (sílaba forte no meio)', 'Proparoxítona'], 'resposta' => 'Oxítona (sílaba forte no final)', 'explicacao' => 'A última sílaba (FÉ) é a mais forte.', 'emoji' => '☕'],
            ],
        ],
        'ano4' => [
            'titulo' => 'Português 4º Ano',
            'faixa' => '9 a 10 anos',
            'introducao' => 'Vamos analisar pronomes, tempos verbais, acentuação e produção textual.',
            'questoes' => [
                ['pergunta' => 'Na frase "Ele comeu o lanche", a palavra "Ele" é um:', 'opcoes' => ['Pronome', 'Adjetivo', 'Substantivo'], 'resposta' => 'Pronome', 'explicacao' => 'Os pronomes substituem os nomes (ex: Ele no lugar de João).', 'emoji' => '👦'],
                ['pergunta' => 'Qual frase está no FUTURO?', 'opcoes' => ['Eu viajarei amanhã.', 'Eu viajei ontem.', 'Eu viajo hoje.'], 'resposta' => 'Eu viajarei amanhã.', 'explicacao' => 'Viajarei indica uma ação que ainda vai acontecer.', 'emoji' => '✈️'],
                ['pergunta' => 'A palavra "PÁSSARO" leva acento porque:', 'opcoes' => ['Todas as proparoxítonas são acentuadas', 'Termina com O', 'Não tem motivo'], 'resposta' => 'Todas as proparoxítonas são acentuadas', 'explicacao' => 'A sílaba tônica é a antepenúltima (PÁS).', 'emoji' => '🐦'],
                ['pergunta' => 'Qual par de palavras são Sinônimos (têm o mesmo sentido)?', 'opcoes' => ['Alegre e Contente', 'Lindo e Feio', 'Dia e Noite'], 'resposta' => 'Alegre e Contente', 'explicacao' => 'Sinônimos são palavras diferentes com significados iguais ou muito parecidos.', 'emoji' => '😁'],
                ['pergunta' => 'Na frase "A menina gosta de ler", o verbo está no infinitivo (sua forma base). Qual é?', 'opcoes' => ['ler', 'menina', 'gosta'], 'resposta' => 'ler', 'explicacao' => 'Os verbos no infinitivo terminam em AR, ER, IR.', 'emoji' => '📖'],
                ['pergunta' => 'O que usamos para indicar a fala de um personagem em uma história?', 'opcoes' => ['Travessão (—)', 'Ponto Final (.)', 'Ponto e vírgula (;)'], 'resposta' => 'Travessão (—)', 'explicacao' => 'O travessão introduz o discurso direto.', 'emoji' => '💬'],
                ['pergunta' => 'Em "Cachorro-quente", temos uma palavra formada por:', 'opcoes' => ['Composição (duas palavras que viram uma)', 'Apenas um adjetivo', 'Verbo e Nome'], 'resposta' => 'Composição (duas palavras que viram uma)', 'explicacao' => 'Duas palavras com hífen que formam um novo significado (Substantivo Composto).', 'emoji' => '🌭'],
                ['pergunta' => 'A frase "Eu não quero ir." tem sentido:', 'opcoes' => ['Negativo', 'Afirmativo', 'Interrogativo'], 'resposta' => 'Negativo', 'explicacao' => 'A palavra "não" exprime negação.', 'emoji' => '🚫'],
                ['pergunta' => 'Qual palavra indica o lugar onde as ações da história acontecem?', 'opcoes' => ['Cenário / Espaço', 'Personagem', 'Tempo'], 'resposta' => 'Cenário / Espaço', 'explicacao' => 'O cenário é o ambiente físico da narrativa.', 'emoji' => '🎭'],
                ['pergunta' => 'Encontre a grafia correta com X ou CH:', 'opcoes' => ['Xícara', 'Chícara', 'Chicara'], 'resposta' => 'Xícara', 'explicacao' => 'A palavra xícara escreve-se sempre com X.', 'emoji' => '☕'],
                ['pergunta' => 'Qual conjunção dá ideia de adição na frase: "Estudei ___ brinquei"?', 'opcoes' => ['e', 'mas', 'ou'], 'resposta' => 'e', 'explicacao' => 'O "e" soma as duas ações (estudar + brincar).', 'emoji' => '➕'],
                ['pergunta' => 'Na frase "Nós fomos ao cinema", o verbo concorda com qual pessoa?', 'opcoes' => ['1ª pessoa do plural (Nós)', '3ª pessoa (Eles)', '1ª pessoa do singular (Eu)'], 'resposta' => '1ª pessoa do plural (Nós)', 'explicacao' => '"Fomos" é conjugado para o pronome "Nós".', 'emoji' => '🎬'],
                ['pergunta' => 'Um texto poético é dividido em linhas e blocos chamados:', 'opcoes' => ['Versos e Estrofes', 'Parágrafos e Capítulos', 'Notícias e Manchetes'], 'resposta' => 'Versos e Estrofes', 'explicacao' => 'O poema usa versos (cada linha) e estrofes (o grupo de linhas).', 'emoji' => '📜'],
                ['pergunta' => 'Qual palavra é um numeral?', 'opcoes' => ['Primeiro', 'Feliz', 'Correr'], 'resposta' => 'Primeiro', 'explicacao' => 'Primeiro é um numeral ordinal que indica posição/ordem.', 'emoji' => '🥇'],
                ['pergunta' => 'Quando lemos uma reportagem no jornal, ela serve para:', 'opcoes' => ['Informar sobre um fato real', 'Contar um conto de fadas', 'Ensinar uma receita'], 'resposta' => 'Informar sobre um fato real', 'explicacao' => 'Textos jornalísticos têm a função de informar.', 'emoji' => '📰'],
                ['pergunta' => 'A separação de sílabas correta da palavra "PÁSSARO" é:', 'opcoes' => ['PÁS-SA-RO', 'PÁ-SSA-RO', 'PASSA-RO'], 'resposta' => 'PÁS-SA-RO', 'explicacao' => 'Letras iguais como "SS" não ficam na mesma sílaba.', 'emoji' => '🐦'],
                ['pergunta' => 'A frase "Puxa, que lindo!" expressa:', 'opcoes' => ['Admiração/Emoção', 'Uma dúvida', 'Uma ordem'], 'resposta' => 'Admiração/Emoção', 'explicacao' => 'A interjeição "Puxa!" junto da exclamação marcam o sentimento.', 'emoji' => '✨'],
                ['pergunta' => 'Qual palavra é paroxítona terminada em ditongo e por isso leva acento?', 'opcoes' => ['História', 'Café', 'Sabiá'], 'resposta' => 'História', 'explicacao' => 'His-tó-ria. A sílaba forte é TÓ e termina em ia (ditongo).', 'emoji' => '📖'],
                ['pergunta' => 'Se o cachorro é "manso", o antônimo seria:', 'opcoes' => ['Bravo', 'Peludo', 'Pequeno'], 'resposta' => 'Bravo', 'explicacao' => 'Bravo ou feroz é o oposto de manso.', 'emoji' => '🐕'],
                ['pergunta' => 'Em "Caminhamos rapidamente", a palavra "rapidamente" indica:', 'opcoes' => ['Modo', 'Lugar', 'Tempo'], 'resposta' => 'Modo', 'explicacao' => 'Indica a maneira (como) a ação foi feita.', 'emoji' => '🏃'],
            ],
        ],
        'ano5' => [
            'titulo' => 'Português 5º Ano',
            'faixa' => '10 a 11 anos',
            'introducao' => 'Vamos focar em coesão, coerência, tipos de texto e interpretação profunda.',
            'questoes' => [
                ['pergunta' => 'O que garante que um texto faça sentido do começo ao fim?', 'opcoes' => ['Coerência', 'Rimas', 'Apenas ter letras maiúsculas'], 'resposta' => 'Coerência', 'explicacao' => 'A coerência é a lógica interna que dá sentido ao texto.', 'emoji' => '🧠'],
                ['pergunta' => 'No texto: "O menino caiu, porém não chorou." A conjunção "porém" indica:', 'opcoes' => ['Ideia de oposição', 'Soma de ideias', 'Causa da queda'], 'resposta' => 'Ideia de oposição', 'explicacao' => 'Porém (como mas, contudo) introduz uma quebra de expectativa.', 'emoji' => '🤕'],
                ['pergunta' => 'A locução adjetiva "de rei" pode ser substituída pelo adjetivo:', 'opcoes' => ['Real', 'Reino', 'Régio (ou Real)'], 'resposta' => 'Régio (ou Real)', 'explicacao' => 'Um tratamento de rei é um tratamento real.', 'emoji' => '👑'],
                ['pergunta' => 'Leia: "A noite estava calma e as estrelas brilhavam." A vírgula (se houvesse) antes do "e" seria errada, por quê?', 'opcoes' => ['Porque não se separa sujeito de verbo sem motivo.', 'Porque a regra é sempre usar.', 'Porque as estrelas são brilhantes.'], 'resposta' => 'Porque não se separa sujeito de verbo sem motivo.', 'explicacao' => 'Neste caso, o aditivo "e" liga orações, mas a pontuação básica pede evitar vírgula antes do e se os sujeitos não mudam bruscamente.', 'emoji' => '⭐'],
                ['pergunta' => 'Qual é o sentido figurado (conotativo) na frase: "João é um touro trabalhando"?', 'opcoes' => ['João é forte/trabalhador', 'João tem chifres', 'João vive no pasto'], 'resposta' => 'João é forte/trabalhador', 'explicacao' => 'Foi usada uma metáfora para indicar a força dele.', 'emoji' => '🐂'],
                ['pergunta' => 'Se o texto diz "O gato pulou graciosamente", "graciosamente" é um advérbio de:', 'opcoes' => ['Modo', 'Tempo', 'Intensidade'], 'resposta' => 'Modo', 'explicacao' => 'O sufixo "mente" normalmente forma advérbios de modo.', 'emoji' => '🐈'],
                ['pergunta' => 'Um texto com opinião do autor sobre uma notícia é um:', 'opcoes' => ['Artigo de opinião', 'Fábula', 'Receita culinária'], 'resposta' => 'Artigo de opinião', 'explicacao' => 'Textos argumentativos expõem o ponto de vista do autor.', 'emoji' => '✍️'],
                ['pergunta' => 'O trecho "A árvore era alta." Qual adjetivo está flexionado no grau superlativo?', 'opcoes' => ['Altíssima', 'Mais alta que', 'Alta'], 'resposta' => 'Altíssima', 'explicacao' => 'O superlativo absoluto sintético de alta é altíssima.', 'emoji' => '🌲'],
                ['pergunta' => 'Leia: "Os alunos compraram os livros. Eles adoraram a leitura". O pronome "Eles" se refere a quem?', 'opcoes' => ['Aos alunos', 'Aos livros', 'À leitura'], 'resposta' => 'Aos alunos', 'explicacao' => 'A coesão textual usa pronomes para evitar repetições.', 'emoji' => '👦'],
                ['pergunta' => 'O texto conta sobre um rio muito calmo. Qual palavra é sinônimo literário para calmo?', 'opcoes' => ['Sereno', 'Agitado', 'Veloz'], 'resposta' => 'Sereno', 'explicacao' => 'Sereno indica algo pacífico, brando e calmo.', 'emoji' => '🌊'],
                ['pergunta' => 'Identifique o erro de concordância: "Nós vai no parque amanhã". O correto é:', 'opcoes' => ['Nós vamos ao parque amanhã', 'A gente vamos no parque', 'Nós fomos ao parque amanhã'], 'resposta' => 'Nós vamos ao parque amanhã', 'explicacao' => 'O pronome "Nós" exige o verbo na 1ª pessoa do plural.', 'emoji' => '🎢'],
                ['pergunta' => 'O verbo no tempo Pretérito Perfeito indica algo que:', 'opcoes' => ['Começou e terminou no passado', 'Ainda está acontecendo', 'Vai acontecer amanhã'], 'resposta' => 'Começou e terminou no passado', 'explicacao' => 'Ex: "Eu li o livro". A ação foi completamente finalizada.', 'emoji' => '🕰️'],
                ['pergunta' => 'Nas histórias em quadrinhos, os balões com "nuvenzinhas" indicam:', 'opcoes' => ['Pensamento', 'Grito', 'Fala comum'], 'resposta' => 'Pensamento', 'explicacao' => 'Balões em formato de nuvem com bolinhas mostram o que o personagem pensa.', 'emoji' => '💭'],
                ['pergunta' => 'Na frase "A menina dividiu o bolo", quem é o objeto direto da ação?', 'opcoes' => ['o bolo', 'a menina', 'dividiu'], 'resposta' => 'o bolo', 'explicacao' => 'O bolo é o alvo da ação de dividir feita pela menina.', 'emoji' => '🍰'],
                ['pergunta' => 'Qual palavra tem um Hífen (-) usado corretamente?', 'opcoes' => ['Guarda-chuva', 'Cachorro-quente', 'Ambas estão certas'], 'resposta' => 'Ambas estão certas', 'explicacao' => 'São palavras compostas que mantêm o hífen pelas regras ortográficas.', 'emoji' => '🌂'],
                ['pergunta' => 'Quando um texto relata as memórias e a vida de uma pessoa importante, escrito por ela mesma, chamamos de:', 'opcoes' => ['Autobiografia', 'Bula de Remédio', 'Diário fictício'], 'resposta' => 'Autobiografia', 'explicacao' => 'Auto (si mesmo) + bio (vida) + grafia (escrita).', 'emoji' => '📖'],
                ['pergunta' => 'Em "Foi o vento QUE derrubou o vaso", a palavra em destaque atua como:', 'opcoes' => ['Pronome Relativo', 'Verbo', 'Adjetivo'], 'resposta' => 'Pronome Relativo', 'explicacao' => 'Retoma o termo anterior (vento) conectando a frase.', 'emoji' => '💨'],
                ['pergunta' => 'Uso de Porque, Por que, Porquê, Por quê. Em perguntas no início da frase, usamos:', 'opcoes' => ['Por que (separado e sem acento)', 'Porque (junto)', 'Porquê (junto com acento)'], 'resposta' => 'Por que (separado e sem acento)', 'explicacao' => 'Início de interrogação sempre se usa "Por que".', 'emoji' => '❓'],
                ['pergunta' => 'A floresta era silenciosa. Qual figura de linguagem usamos ao dizer "A floresta sussurrava segredos"?', 'opcoes' => ['Personificação (Dar vida a seres inanimados)', 'Metáfora', 'Hipérbole (Exagero)'], 'resposta' => 'Personificação (Dar vida a seres inanimados)', 'explicacao' => 'Demos características humanas (sussurrar) à floresta.', 'emoji' => '🌲'],
                ['pergunta' => 'Complete com MAS ou MAIS: "Eu quero brincar, ___ tenho que estudar primeiro."', 'opcoes' => ['MAS', 'MAIS', 'As duas servem'], 'resposta' => 'MAS', 'explicacao' => 'MAS indica oposição/contraste. MAIS indica quantidade.', 'emoji' => '📚'],
            ],
        ],
    ],
    'ingles' => [
        'ano1' => [
            'titulo' => 'Inglês 1º Ano',
            'faixa' => '6 a 7 anos',
            'introducao' => 'Aprender cores, animais básicos e números em inglês.',
            'questoes' => [
                ['pergunta' => 'What color is the sky?', 'opcoes' => ['Blue', 'Red', 'Green'], 'resposta' => 'Blue', 'explicacao' => 'The sky is blue on a sunny day.', 'emoji' => '🌤️'],
                ['pergunta' => 'What color is an apple usually?', 'opcoes' => ['Red', 'Purple', 'Black'], 'resposta' => 'Red', 'explicacao' => 'Apples are usually red or green.', 'emoji' => '🍎'],
                ['pergunta' => 'What color is a banana?', 'opcoes' => ['Yellow', 'Blue', 'Black'], 'resposta' => 'Yellow', 'explicacao' => 'Bananas are yellow when they are ripe.', 'emoji' => '🍌'],
                ['pergunta' => 'What word means the animal that says "meow"?', 'opcoes' => ['Cat', 'Dog', 'Cow'], 'resposta' => 'Cat', 'explicacao' => 'The animal that says meow is a cat.', 'emoji' => '🐈'],
                ['pergunta' => 'What is the number 1 in English?', 'opcoes' => ['One', 'Two', 'Three'], 'resposta' => 'One', 'explicacao' => 'O número um em inglês se diz "One".', 'emoji' => '1️⃣'],
                ['pergunta' => 'What color is grass?', 'opcoes' => ['Green', 'Red', 'Purple'], 'resposta' => 'Green', 'explicacao' => 'Grass (grama) is green outside.', 'emoji' => '🌱'],
                ['pergunta' => 'How do we say "Oi" in English?', 'opcoes' => ['Hi / Hello', 'Goodbye', 'Please'], 'resposta' => 'Hi / Hello', 'explicacao' => 'Usamos Hello ou Hi para dizer Oi.', 'emoji' => '👋'],
                ['pergunta' => 'What is the number 3 in English?', 'opcoes' => ['Three', 'Five', 'Four'], 'resposta' => 'Three', 'explicacao' => 'Um, dois, TRÊS: One, two, THREE.', 'emoji' => '3️⃣'],
                ['pergunta' => 'What word means the animal that says "woof"?', 'opcoes' => ['Dog', 'Cat', 'Cow'], 'resposta' => 'Dog', 'explicacao' => 'Dog says woof.', 'emoji' => '🐕'],
                ['pergunta' => 'Which word means a house?', 'opcoes' => ['House / Home', 'Car', 'Tree'], 'resposta' => 'House / Home', 'explicacao' => 'House is the word for casa.', 'emoji' => '🏠'],
                ['pergunta' => 'What color is the moon?', 'opcoes' => ['White', 'Pink', 'Orange'], 'resposta' => 'White', 'explicacao' => 'The moon is white (branca) in the night sky.', 'emoji' => '🌕'],
                ['pergunta' => 'How do we say "Obrigado"?', 'opcoes' => ['Thank you', 'Yes', 'No'], 'resposta' => 'Thank you', 'explicacao' => 'Thank you means obrigado.', 'emoji' => '🙏'],
                ['pergunta' => 'What is the number 5?', 'opcoes' => ['Five', 'Ten', 'Two'], 'resposta' => 'Five', 'explicacao' => 'The number 5 is Five.', 'emoji' => '5️⃣'],
                ['pergunta' => 'Which word is an animal with a long trunk (tromba)?', 'opcoes' => ['Elephant', 'Tiger', 'Bird'], 'resposta' => 'Elephant', 'explicacao' => 'Elephant is the animal with a trunk.', 'emoji' => '🐘'],
                ['pergunta' => 'What color is the frog?', 'opcoes' => ['Green', 'Brown', 'Blue'], 'resposta' => 'Green', 'explicacao' => 'The frog (sapo) is green.', 'emoji' => '🐸'],
                ['pergunta' => 'What is a "Boy"?', 'opcoes' => ['Um menino', 'Uma menina', 'Um cachorro'], 'resposta' => 'Um menino', 'explicacao' => 'Boy significa menino.', 'emoji' => '👦'],
                ['pergunta' => 'What is a "Girl"?', 'opcoes' => ['Uma menina', 'Um menino', 'Um gato'], 'resposta' => 'Uma menina', 'explicacao' => 'Girl significa menina.', 'emoji' => '👧'],
                ['pergunta' => 'How do we say "Tchau"?', 'opcoes' => ['Bye / Goodbye', 'Hello', 'Please'], 'resposta' => 'Bye / Goodbye', 'explicacao' => 'Goodbye é a forma de despedida.', 'emoji' => '👋'],
                ['pergunta' => 'What color is a lemon?', 'opcoes' => ['Yellow', 'Green', 'Blue'], 'resposta' => 'Yellow', 'explicacao' => 'A lemon (limão siciliano) is yellow.', 'emoji' => '🍋'],
                ['pergunta' => 'Which animal swims in the water?', 'opcoes' => ['Fish', 'Bird', 'Monkey'], 'resposta' => 'Fish', 'explicacao' => 'Fish (peixe) swims in the water.', 'emoji' => '🐟'],
            ],
        ],
        'ano2' => [
            'titulo' => 'Inglês 2º Ano',
            'faixa' => '7 a 8 anos',
            'introducao' => 'Vamos aprender objetos escolares, membros da família e dias da semana.',
            'questoes' => [
                ['pergunta' => 'How do we say "Mãe" in English?', 'opcoes' => ['Mother (Mom)', 'Father (Dad)', 'Brother'], 'resposta' => 'Mother (Mom)', 'explicacao' => 'Mother ou Mom significa mãe.', 'emoji' => '👩‍👦'],
                ['pergunta' => 'Which animal is small and likes cheese?', 'opcoes' => ['Mouse', 'Lion', 'Horse'], 'resposta' => 'Mouse', 'explicacao' => 'A mouse (rato) is small and likes cheese.', 'emoji' => '🐭'],
                ['pergunta' => 'What is a "Book"?', 'opcoes' => ['Um livro', 'Um lápis', 'Uma borracha'], 'resposta' => 'Um livro', 'explicacao' => 'Usamos o book para ler.', 'emoji' => '📚'],
                ['pergunta' => 'How do we say "Pai" in English?', 'opcoes' => ['Father (Dad)', 'Sister', 'Uncle'], 'resposta' => 'Father (Dad)', 'explicacao' => 'Father ou Dad significa pai.', 'emoji' => '👨‍👧'],
                ['pergunta' => 'What is a "Pencil"?', 'opcoes' => ['Um lápis', 'Uma caneta', 'Uma mesa'], 'resposta' => 'Um lápis', 'explicacao' => 'Pencil é usado para escrever e desenhar.', 'emoji' => '✏️'],
                ['pergunta' => 'Which animal is described by "long neck, eats leaves"?', 'opcoes' => ['Giraffe', 'Elephant', 'Rabbit'], 'resposta' => 'Giraffe', 'explicacao' => 'A giraffe has a long neck.', 'emoji' => '🦒'],
                ['pergunta' => 'What is the color of the Sun?', 'opcoes' => ['Yellow', 'Pink', 'Black'], 'resposta' => 'Yellow', 'explicacao' => 'The sun is yellow (amarelo).', 'emoji' => '☀️'],
                ['pergunta' => 'What is the animal that likes carrots and hops?', 'opcoes' => ['Rabbit', 'Cat', 'Frog'], 'resposta' => 'Rabbit', 'explicacao' => 'A rabbit (coelho) likes carrots and hops.', 'emoji' => '🐰'],
                ['pergunta' => 'Which word means the sound "moo"?', 'opcoes' => ['Cow', 'Dog', 'Cat'], 'resposta' => 'Cow', 'explicacao' => 'Cow (vaca) says moo.', 'emoji' => '🐄'],
                ['pergunta' => 'How do we say "Bom dia"?', 'opcoes' => ['Good morning', 'Good night', 'Good afternoon'], 'resposta' => 'Good morning', 'explicacao' => 'Morning significa manhã.', 'emoji' => '🌅'],
                ['pergunta' => 'What is an "Eraser"?', 'opcoes' => ['Uma borracha', 'Um caderno', 'Um estojo'], 'resposta' => 'Uma borracha', 'explicacao' => 'Eraser é a borracha de apagar.', 'emoji' => '🧽'],
                ['pergunta' => 'Which animal has stripes and lives in the jungle?', 'opcoes' => ['Tiger', 'Horse', 'Monkey'], 'resposta' => 'Tiger', 'explicacao' => 'A tiger (tigre) has stripes.', 'emoji' => '🐅'],
                ['pergunta' => 'What word means the season when it is very cold?', 'opcoes' => ['Winter', 'Summer', 'Autumn'], 'resposta' => 'Winter', 'explicacao' => 'Winter é o inverno.', 'emoji' => '❄️'],
                ['pergunta' => 'How do we say "Irmão"?', 'opcoes' => ['Brother', 'Sister', 'Baby'], 'resposta' => 'Brother', 'explicacao' => 'Brother é irmão menino.', 'emoji' => '👦'],
                ['pergunta' => 'How do we say "Irmã"?', 'opcoes' => ['Sister', 'Mother', 'Aunt'], 'resposta' => 'Sister', 'explicacao' => 'Sister é irmã menina.', 'emoji' => '👧'],
                ['pergunta' => 'Which word is the opposite of HOT (Quente)?', 'opcoes' => ['Cold (Frio)', 'Warm (Morno)', 'Bright (Brilhante)'], 'resposta' => 'Cold (Frio)', 'explicacao' => 'Cold is the opposite of hot.', 'emoji' => '🥶'],
                ['pergunta' => 'Which animal hops and says ribbit?', 'opcoes' => ['Frog', 'Bird', 'Fish'], 'resposta' => 'Frog', 'explicacao' => 'A frog (sapo) hops and says ribbit.', 'emoji' => '🐸'],
                ['pergunta' => 'What falls from the clouds? (Ra _ n)', 'opcoes' => ['Rain', 'Ran', 'Ring'], 'resposta' => 'Rain', 'explicacao' => 'Rain é chuva.', 'emoji' => '🌧️'],
                ['pergunta' => 'What do we say when we go to sleep?', 'opcoes' => ['Good night', 'Good morning', 'Hello'], 'resposta' => 'Good night', 'explicacao' => 'Usamos Good night para nos despedirmos à noite.', 'emoji' => '🌜'],
                ['pergunta' => 'Which word means a place where we learn?', 'opcoes' => ['School', 'Store', 'Car'], 'resposta' => 'School', 'explicacao' => 'School is the place where we learn (escola).', 'emoji' => '🏫'],
            ],
        ],
        'ano3' => [
            'titulo' => 'Inglês 3º Ano',
            'faixa' => '8 a 9 anos',
            'introducao' => 'Vamos trabalhar com verbos de ação, partes do corpo e frases curtas.',
            'questoes' => [
                ['pergunta' => 'The children "play" outside. What does "play" mean?', 'opcoes' => ['Brincar / Jogar', 'Dormir', 'Comer'], 'resposta' => 'Brincar / Jogar', 'explicacao' => 'To play significa brincar, jogar ou tocar um instrumento.', 'emoji' => '⚽'],
                ['pergunta' => 'The bird "sings" on the tree. What does it do?', 'opcoes' => ['Canta', 'Dança', 'Corre'], 'resposta' => 'Canta', 'explicacao' => 'Sing em inglês é cantar.', 'emoji' => '🎶'],
                ['pergunta' => 'What part of the body do we use to see? (Olhos)', 'opcoes' => ['Eyes', 'Ears', 'Nose'], 'resposta' => 'Eyes', 'explicacao' => 'Eyes são os nossos olhos.', 'emoji' => '👁️'],
                ['pergunta' => 'The dog "runs" fast. What does the dog do?', 'opcoes' => ['Corre', 'Dorme', 'Come'], 'resposta' => 'Corre', 'explicacao' => 'Run significa correr.', 'emoji' => '🐕'],
                ['pergunta' => 'What part of the body do we use to hear? (Orelhas)', 'opcoes' => ['Ears', 'Mouth', 'Hands'], 'resposta' => 'Ears', 'explicacao' => 'Ears são os ouvidos/orelhas.', 'emoji' => '👂'],
                ['pergunta' => 'The boy eats an apple. What is he doing?', 'opcoes' => ['Comendo', 'Brincando', 'Lendo'], 'resposta' => 'Comendo', 'explicacao' => 'Eat significa comer.', 'emoji' => '🍎'],
                ['pergunta' => 'What is a "Head"?', 'opcoes' => ['Cabeça', 'Pé', 'Braço'], 'resposta' => 'Cabeça', 'explicacao' => 'Head é a nossa cabeça.', 'emoji' => '🗣️'],
                ['pergunta' => 'The fish "swim" in the river. What is "swim"?', 'opcoes' => ['Nadar', 'Voar', 'Pular'], 'resposta' => 'Nadar', 'explicacao' => 'Swim significa nadar.', 'emoji' => '🐟'],
                ['pergunta' => 'How do we say "Eu gosto de maçãs"?', 'opcoes' => ['I like apples', 'I hate apples', 'I see apples'], 'resposta' => 'I like apples', 'explicacao' => '"I like" expressa que você gosta de algo.', 'emoji' => '👍'],
                ['pergunta' => 'My friend has a red bike. What does he have?', 'opcoes' => ['Uma bicicleta vermelha', 'Um carro azul', 'Uma bola verde'], 'resposta' => 'Uma bicicleta vermelha', 'explicacao' => 'Red = vermelho, Bike = bicicleta.', 'emoji' => '🚲'],
                ['pergunta' => 'Which animal is BIG?', 'opcoes' => ['The elephant', 'The mouse', 'The ant'], 'resposta' => 'The elephant', 'explicacao' => 'Big significa grande.', 'emoji' => '🐘'],
                ['pergunta' => 'The sun "warms" the flowers. O que o sol faz?', 'opcoes' => ['Aquece', 'Esfria', 'Congela'], 'resposta' => 'Aquece', 'explicacao' => 'Warm significa aquecer.', 'emoji' => '☀️'],
                ['pergunta' => 'Which word is a piece of clothing for our feet?', 'opcoes' => ['Shoes (sapatos)', 'Hat (chapéu)', 'Shirt (camisa)'], 'resposta' => 'Shoes (sapatos)', 'explicacao' => 'Usamos shoes nos pés.', 'emoji' => '👟'],
                ['pergunta' => 'My sister "drinks" milk. What does she do?', 'opcoes' => ['Bebe', 'Come', 'Canta'], 'resposta' => 'Bebe', 'explicacao' => 'Drink significa beber algo.', 'emoji' => '🥛'],
                ['pergunta' => 'What color are the leaves on a healthy tree?', 'opcoes' => ['Green', 'Red', 'Brown'], 'resposta' => 'Green', 'explicacao' => 'Folhas saudáveis (leaves) geralmente são verdes (green).', 'emoji' => '🍃'],
                ['pergunta' => 'How do we say "Feliz" in English?', 'opcoes' => ['Happy', 'Sad', 'Angry'], 'resposta' => 'Happy', 'explicacao' => 'Happy é o estado de estar feliz.', 'emoji' => '😊'],
                ['pergunta' => 'If someone is "Sad", how are they feeling?', 'opcoes' => ['Triste', 'Feliz', 'Bravo'], 'resposta' => 'Triste', 'explicacao' => 'Sad significa estar triste.', 'emoji' => '😢'],
                ['pergunta' => 'The pink flower "smells" nice. What does it do?', 'opcoes' => ['Cheira bem', 'Corre rápido', 'Faz barulho'], 'resposta' => 'Cheira bem', 'explicacao' => 'Smell refere-se ao sentido do olfato/cheiro.', 'emoji' => '👃'],
                ['pergunta' => 'What is the opposite of BIG?', 'opcoes' => ['Small', 'Tall', 'Fast'], 'resposta' => 'Small', 'explicacao' => 'Small (pequeno) é o contrário de Big (grande).', 'emoji' => '🐜'],
                ['pergunta' => 'What is a "T-shirt"?', 'opcoes' => ['Camiseta', 'Calça', 'Meia'], 'resposta' => 'Camiseta', 'explicacao' => 'T-shirt é uma blusa/camiseta comum.', 'emoji' => '👕'],
            ],
        ],
        'ano4' => [
            'titulo' => 'Inglês 4º Ano',
            'faixa' => '9 a 10 anos',
            'introducao' => 'Gramática inicial, tempos contínuos (ing), lugares da cidade e natureza.',
            'questoes' => [
                ['pergunta' => 'Which sentence is grammatically correct?', 'opcoes' => ['The bird is flying.', 'The bird are flying.', 'The bird is fly.'], 'resposta' => 'The bird is flying.', 'explicacao' => 'Para um pássaro (it), usamos "is" + o verbo com "ing".', 'emoji' => '🦅'],
                ['pergunta' => 'The sun is bright. What does "bright" mean?', 'opcoes' => ['Brilhante', 'Escuro', 'Frio'], 'resposta' => 'Brilhante', 'explicacao' => 'Bright refere-se a algo que emite muita luz.', 'emoji' => '☀️'],
                ['pergunta' => 'Which word is a place on Earth where there is sand and water?', 'opcoes' => ['Beach', 'Mountain', 'Forest'], 'resposta' => 'Beach', 'explicacao' => 'A beach (praia) tem areia e o oceano.', 'emoji' => '🏖️'],
                ['pergunta' => 'Which sentence uses the plural correctly?', 'opcoes' => ['The cats are sleeping.', 'The cats is sleeping.', 'The cat are sleep.'], 'resposta' => 'The cats are sleeping.', 'explicacao' => 'Para plural (they), usamos o verbo "are".', 'emoji' => '🐈'],
                ['pergunta' => 'Which word means a big body of saltwater?', 'opcoes' => ['Ocean', 'Pond', 'River'], 'resposta' => 'Ocean', 'explicacao' => 'Ocean (Oceano) é a maior massa de água.', 'emoji' => '🌊'],
                ['pergunta' => 'Which sentence describes weather with no sun?', 'opcoes' => ['It is cloudy.', 'It is sunny.', 'It is hot.'], 'resposta' => 'It is cloudy.', 'explicacao' => 'Cloudy significa que está nublado (cheio de nuvens).', 'emoji' => '☁️'],
                ['pergunta' => 'What do you buy at a "Bakery"?', 'opcoes' => ['Bread', 'Books', 'Shoes'], 'resposta' => 'Bread', 'explicacao' => 'Bakery é padaria, onde se compra pão (bread).', 'emoji' => '🍞'],
                ['pergunta' => 'The earth spins and the moon moves around it. What does "around" mean?', 'opcoes' => ['Ao redor / Em volta', 'Em cima', 'Abaixo'], 'resposta' => 'Ao redor / Em volta', 'explicacao' => 'Around indica movimento circular ou em volta de algo.', 'emoji' => '🌍'],
                ['pergunta' => 'Which sentence describes a long river?', 'opcoes' => ['The river is long.', 'The river is tall.', 'The river is short.'], 'resposta' => 'The river is long.', 'explicacao' => 'Usamos long para comprimento.', 'emoji' => '🏞️'],
                ['pergunta' => 'What happens when it is "Rainy"?', 'opcoes' => ['It rains (chove).', 'It snows (neva).', 'The sun shines.'], 'resposta' => 'It rains (chove).', 'explicacao' => 'Rainy weather significa tempo chuvoso.', 'emoji' => '🌧️'],
                ['pergunta' => 'Where can you read and borrow books in the city?', 'opcoes' => ['Library', 'Supermarket', 'Hospital'], 'resposta' => 'Library', 'explicacao' => 'Library (Biblioteca) é o lugar dos livros.', 'emoji' => '📚'],
                ['pergunta' => 'Which sentence is about a high mountain?', 'opcoes' => ['The mountain is high.', 'The mountain is fast.', 'The mountain is loud.'], 'resposta' => 'The mountain is high.', 'explicacao' => 'High é o adjetivo correto para altitude/montanhas.', 'emoji' => '⛰️'],
                ['pergunta' => 'Translate: "Eu estou comendo".', 'opcoes' => ['I am eating.', 'I eat.', 'I was eating.'], 'resposta' => 'I am eating.', 'explicacao' => 'O sufixo "ing" (Present Continuous) mostra algo acontecendo agora.', 'emoji' => '🍽️'],
                ['pergunta' => 'Where do you go when you are sick?', 'opcoes' => ['Hospital', 'Park', 'Cinema'], 'resposta' => 'Hospital', 'explicacao' => 'Médicos trabalham no Hospital para cuidar de quem está doente.', 'emoji' => '🏥'],
                ['pergunta' => 'Which word means a place with many trees and wild animals?', 'opcoes' => ['Forest', 'Market', 'House'], 'resposta' => 'Forest', 'explicacao' => 'A forest (floresta) é cheia de natureza livre.', 'emoji' => '🌲'],
                ['pergunta' => 'In a sentence: "She ___ reading a book."', 'opcoes' => ['is', 'are', 'am'], 'resposta' => 'is', 'explicacao' => 'Com She, He ou It, usamos o verbo "is".', 'emoji' => '📖'],
                ['pergunta' => 'Which word describes a place where airplanes land?', 'opcoes' => ['Airport', 'Harbor', 'Train station'], 'resposta' => 'Airport', 'explicacao' => 'Airport é aeroporto.', 'emoji' => '✈️'],
                ['pergunta' => 'What is the opposite of FAST?', 'opcoes' => ['Slow', 'Quick', 'Loud'], 'resposta' => 'Slow', 'explicacao' => 'Slow (devagar) é o contrário de Fast (rápido).', 'emoji' => '🐢'],
                ['pergunta' => 'Which word means a place where we see animals from around the world in enclosures?', 'opcoes' => ['Zoo', 'Store', 'Library'], 'resposta' => 'Zoo', 'explicacao' => 'Zoo (Zoológico) abriga diversos animais.', 'emoji' => '🦓'],
                ['pergunta' => 'Complete: "I ___ a student."', 'opcoes' => ['am', 'is', 'are'], 'resposta' => 'am', 'explicacao' => 'O pronome I (eu) sempre vem acompanhado de "am".', 'emoji' => '🎓'],
            ],
        ],
        'ano5' => [
            'titulo' => 'Inglês 5º Ano',
            'faixa' => '10 a 11 anos',
            'introducao' => 'Vamos treinar interpretação de textos curtos, vocabulário e pronomes.',
            'questoes' => [
                ['pergunta' => 'Read: "Anna walks to school every day." What does she do?', 'opcoes' => ['She goes to school on foot.', 'She drives a car.', 'She sleeps at school.'], 'resposta' => 'She goes to school on foot.', 'explicacao' => 'Walks significa caminhar, ir a pé (on foot).', 'emoji' => '🚶‍♀️'],
                ['pergunta' => 'The park is "quiet" in the morning. Which word is a synonym for quiet?', 'opcoes' => ['Silent', 'Loud', 'Fast'], 'resposta' => 'Silent', 'explicacao' => 'Silent (silencioso) tem o mesmo sentido que quiet.', 'emoji' => '🤫'],
                ['pergunta' => 'He shares his snack with a friend. What does "shares" mean?', 'opcoes' => ['Divide / Compartilha', 'Esconde', 'Come sozinho'], 'resposta' => 'Divide / Compartilha', 'explicacao' => 'To share é um ato de amizade: compartilhar.', 'emoji' => '🥪'],
                ['pergunta' => 'The text says: "The blue bird flew over the garden." What is the past tense of FLY?', 'opcoes' => ['Flew', 'Flyed', 'Flown'], 'resposta' => 'Flew', 'explicacao' => 'Flew é o verbo irregular passado de Fly.', 'emoji' => '🕊️'],
                ['pergunta' => 'What is the opposite of EXPENSIVE (Caro)?', 'opcoes' => ['Cheap (Barato)', 'Rich (Rico)', 'Big (Grande)'], 'resposta' => 'Cheap (Barato)', 'explicacao' => 'Cheap é o contrário de Expensive.', 'emoji' => '💰'],
                ['pergunta' => 'In the text, the child finds a "lost puppy". O que é um puppy?', 'opcoes' => ['Filhote de cachorro', 'Um brinquedo', 'Um gato adulto'], 'resposta' => 'Filhote de cachorro', 'explicacao' => 'Puppy refere-se a um cachorrinho jovem.', 'emoji' => '🐶'],
                ['pergunta' => 'Which word is similar in meaning to HAPPY?', 'opcoes' => ['Glad', 'Sad', 'Angry'], 'resposta' => 'Glad', 'explicacao' => 'Glad significa estar contente ou satisfeito.', 'emoji' => '😁'],
                ['pergunta' => 'Complete the daily routine: "I wake ___ at 7 AM."', 'opcoes' => ['up', 'down', 'in'], 'resposta' => 'up', 'explicacao' => 'O verbo frasal é Wake up (acordar).', 'emoji' => '⏰'],
                ['pergunta' => 'The river flows "gently". Which word means gently?', 'opcoes' => ['Softly / Suavemente', 'Loudly / Alto', 'Quickly / Rápido'], 'resposta' => 'Softly / Suavemente', 'explicacao' => 'Gently indica algo delicado, feito com suavidade.', 'emoji' => '🌊'],
                ['pergunta' => 'The children "help each other". What do they do?', 'opcoes' => ['Eles se ajudam', 'Eles brigam', 'Eles se ignoram'], 'resposta' => 'Eles se ajudam', 'explicacao' => '"Each other" expressa reciprocidade (um ao outro).', 'emoji' => '🤝'],
                ['pergunta' => 'Which word means the same as FAST?', 'opcoes' => ['Quick', 'Slow', 'Small'], 'resposta' => 'Quick', 'explicacao' => 'Quick e Fast são sinônimos de rápido.', 'emoji' => '⚡'],
                ['pergunta' => 'What is the opposite of EMPTY (Vazio)?', 'opcoes' => ['Full (Cheio)', 'Dry (Seco)', 'Cold (Frio)'], 'resposta' => 'Full (Cheio)', 'explicacao' => 'Um copo que não está vazio, está Full (cheio).', 'emoji' => '🥛'],
                ['pergunta' => 'The girl planted a tree in the "yard". Where is the yard?', 'opcoes' => ['No quintal', 'No telhado', 'No quarto'], 'resposta' => 'No quintal', 'explicacao' => 'Yard é a área ao ar livre da casa, o quintal ou pátio.', 'emoji' => '🏡'],
                ['pergunta' => 'Which word means the same as BIG?', 'opcoes' => ['Large', 'Small', 'Narrow'], 'resposta' => 'Large', 'explicacao' => 'Large e Big são palavras que indicam grande tamanho.', 'emoji' => '🐘'],
                ['pergunta' => 'The story says the fox was "clever". What is another word for clever?', 'opcoes' => ['Smart', 'Funny', 'Slow'], 'resposta' => 'Smart', 'explicacao' => 'Clever (esperto) tem significado parecido com Smart (inteligente).', 'emoji' => '🦊'],
                ['pergunta' => 'Which sentence uses the verb TO HAVE correctly?', 'opcoes' => ['She has a dog.', 'She have a dog.', 'She is have a dog.'], 'resposta' => 'She has a dog.', 'explicacao' => 'Para he, she, it, a conjugação de have muda para HAS.', 'emoji' => '🐕'],
                ['pergunta' => 'Which word means the opposite of AWAKE (Acordado)?', 'opcoes' => ['Asleep (Dormindo)', 'Happy (Feliz)', 'Fast (Rápido)'], 'resposta' => 'Asleep (Dormindo)', 'explicacao' => 'Asleep significa o estado de quem está dormindo.', 'emoji' => '😴'],
                ['pergunta' => 'What do you say when you ask for a favor?', 'opcoes' => ['Please', 'Sorry', 'Goodbye'], 'resposta' => 'Please', 'explicacao' => 'Please é "Por favor", usado para pedidos.', 'emoji' => '🙏'],
                ['pergunta' => 'If the text says "The sky is cloudy," which word has the opposite meaning?', 'opcoes' => ['Clear', 'Cold', 'Dark'], 'resposta' => 'Clear', 'explicacao' => 'O oposto de nublado (cloudy) é um céu limpo (clear).', 'emoji' => '🌤️'],
                ['pergunta' => 'Who is your "Uncle"?', 'opcoes' => ['Meu tio', 'Meu pai', 'Meu avô'], 'resposta' => 'Meu tio', 'explicacao' => 'O irmão da sua mãe ou do seu pai é seu Uncle.', 'emoji' => '👨'],
            ],
        ],
    ],
];

?>